apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-server-healthcheck-policy
  namespace: argocd
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        portSpecification: USE_FIXED_PORT
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server