apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:sairinraychoudhury/gitops-argocd-lab.git
        revision: main
        directories:
          - path: apps/*
          - path: apps/widget-crd
            exclude: true

  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: app-team

      source:
        repoURL: git@github.com:sairinraychoudhury/gitops-argocd-lab.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true